/**
 * Generates typed ABIs for viem from the Foundry build output (contracts/out).
 * Run after `forge build`:  npm run abis
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '../../contracts/out')

const CONTRACTS: Record<string, string> = {
  yieldVault: 'YieldVault.sol/YieldVault.json',
  inventoryVault: 'InventoryVault.sol/InventoryVault.json',
  jitLiquidityApp: 'JitLiquidityApp.sol/JitLiquidityApp.json',
  oracleSwapApp: 'OracleSwapApp.sol/OracleSwapApp.json',
  yieldResolver: 'YieldResolver.sol/YieldResolver.json',
  yieldAdapter: 'IYieldAdapter.sol/IYieldAdapter.json',
  erc4626Adapter: 'ERC4626Adapter.sol/ERC4626Adapter.json',
  aaveV3Adapter: 'AaveV3Adapter.sol/AaveV3Adapter.json',
  chainlinkAggregator: 'IChainlinkAggregator.sol/IChainlinkAggregator.json',
  limitOrderProtocol: 'LimitOrderProtocol.sol/LimitOrderProtocol.json',
  mockERC20: 'MockERC20.sol/MockERC20.json',
  mockOracle: 'MockOracle.sol/MockOracle.json',
  mockSwapRouter: 'MockSwapRouter.sol/MockSwapRouter.json',
  mockLendingVault: 'MockLendingVault.sol/MockLendingVault.json',
  mockAavePool: 'MockAavePool.sol/MockAavePool.json',
  aqua: 'Aqua.sol/Aqua.json',
  aquaYieldApp: 'AquaYieldApp.sol/AquaYieldApp.json',
  walletResolver: 'WalletResolver.sol/WalletResolver.json',
  aave4626: 'Aave4626.sol/Aave4626.json',
  carryVault: 'CarryVault.sol/CarryVault.json',
  mockCreditMarket: 'MockCreditMarket.sol/MockCreditMarket.json',
  yieldSwapVMRouter: 'YieldSwapVMRouter.sol/YieldSwapVMRouter.json',
  yieldSwapVMStrategies: 'YieldSwapVMStrategies.sol/YieldSwapVMStrategies.json',
  swapVMResolver: 'SwapVMResolver.sol/SwapVMResolver.json',
}

let src = '// Generated by scripts/gen-abis.ts from contracts/out — do not edit.\n\n'
for (const [name, path] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(readFileSync(join(out, path), 'utf8'))
  src += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const\n\n`
}
writeFileSync(join(here, '../src/abis.ts'), src)
console.log(`wrote ${Object.keys(CONTRACTS).length} ABIs to src/abis.ts`)
